### ISSUE TITLE
Deployment Failure - Requirements Upgrades

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/inventory-app#769]
Workflow with Issue: deploy
Job Failed: deploy
Last Commit: 11a79aacdb9b56bc85b240b36c3ea9a72b038ad1
Number of times run: 3
Last run by: btylerburton
Github Action Run: https://github.com/GSA/inventory-app/actions/runs/10930667554

**Comment by btylerburton** [comment]
Fixed by pinning setuptools: https://github.com/GSA/inventory-app/pull/770
